# Generated by Django 4.0.2 on 2022-02-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_latitude_alter_customuser_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='User', max_length=20),
        ),
    ]
